info:
  idsid: http://plugfest2021.08.localhost.demo
  curator: urn:ids:localhost
  maintainer: urn:ids:localhost
  titles:
    - IDSA Plugfest Localhost Connector
  descriptions:
    - IDSA Plugfest Localhost Connector
  accessUrl:
    - http://core-container-connector-2:8080

broker:
  address: https://broker.test
  id: urn:ids:broker
  autoRegister: false

daps:
  url: https://daps.aisec.fraunhofer.de/v2
  verification: IDSA

keystore:
  type: PEM
  pem:
    cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVRekNDQXl1Z0F3SUJBZ0lDQU5Bd0RRWUpLb1pJaHZjTkFRRUxCUUF3UURFTE1Ba0dBMVVFQmhNQ1JFVXgKRXpBUkJnTlZCQW9NQ2taeVlYVnVhRzltWlhJeEhEQWFCZ05WQkFNTUUwbEVVeUJVWlhOMElGTjFZa05CSURJdwpNVGd3SGhjTk1qRXdPREUyTVRFMU1UVTNXaGNOTWpNd09ERTJNVEUxTVRVM1dqQmxNUXN3Q1FZRFZRUUdFd0pFClJURU1NQW9HQTFVRUNnd0RTVVJUTVJrd0Z3WURWUVFMREJCUWJIVm5abVZ6ZENBeU1ESXhJREE0TVMwd0t3WUQKVlFRRERDUTJZekUzTXpjNU1TMWxaR0UzTFRRMllUSXRPV0poTnkxbU5XSTJaV0l6Tm1RMllqRXdnZ0VpTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREEvVm9PS0hjUFBma2VLQTBlZ2d2V2ZoUXFGYnlrClA4dkRRSitSdG80WG00MlJuNEY5TXRjK3dFZnFPYWhmZTlPSFR6Sms3SUJ2UEdIbUZrY2hIM1Y5VE1Dc1ZiMkkKc2FFemlmeDRZQU9ZL0dlRlErMDNMNm1BaDdCb3B3dm9XcERwdDN1blFqek8zSXE0QjZBc0gwbEw5akxGZ1pseApkOHJnV0oyWXVZbjU4V1NpTWNqQlZtdVdkbTZyTTFmVUNLUWZYQVVLL2dGUlBpa0RHT3BMY0lPMkJGMzB5czFMCmRYaXArS2M3WDQ3ZXNjNDRpUmV3dGU4ZURYb0NERmhyelFEcnZBemQ2T0FGcFU5UWJXQk4vL2YrNFZ6RWN2R1cKZjMvd3RnOW9SRlVtZDJxZHVXVVhIaUhaeExZdkIzSGF3TjFYSk9mZVV3VXNZdjAvUW9tTG90QVBBZ01CQUFHagpnZ0VnTUlJQkhEQWRCZ05WSFE0RUZnUVVpOTd1VEh3dGU1TlJMLzJnMDFOTVdNcWRjTUl3SHdZRFZSMGpCQmd3CkZvQVV5NHpIdG9WNXFDT215eFdyRjFBdjVtVkRYZWd3Q1FZRFZSMFRCQUl3QURBTEJnTlZIUThFQkFNQ0JhQXcKTndZRFZSMGZCREF3TGpBc29DcWdLSVltYUhSMGNEb3ZMMk55YkM1aGFYTmxZeTVtY21GMWJtaHZabVZ5TG1SbApMMmxrY3k1amNtd3dWQVlJS3dZQkJRVUhBUUVFU0RCR01FUUdDQ3NHQVFVRkJ6QUNoamhvZEhSd09pOHZaRzkzCmJteHZZV1J6TG1GcGMyVmpMbVp5WVhWdWFHOW1aWEl1WkdVdmNtOXZkR05oWTJWeWRESXdNVFl1WTJWeWREQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQWdZSUt3WUJCUVVIQXdFd0ZBWURWUjBSQkEwd0M0SUpiRzlqWVd4bwpiM04wTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBOTd6ajVnNjR0RU9QdVkvM3NDRHlrdURZMTJZUisrSVRHClp3QzlsT2hzMkR5VVg3ZEhNZXNnYUVobTFXSEZOc1J1WXpoenh5ZzNkQlVNK1QyNmtpMHIzTXdja3YvcEJzdzAKNVVFUEVwaFBsVGFvdm5pWmRjclVGcGtpYzl5YmZvb2JzVUQxTUtkSnE3MkFRdm1WSHRYWlJXYldpOXRFcFB3MwpyVWhhTkk4SXRMK040MEk3NU5uRHBEdG9zSmtyQ2hleXM3aGpkc2c3UXZ4NGpuNE4xT1o2aGQyMGNTd21sTEpFCmtlVGZKM0REeVEwODRlbk00K3liTVZsVUsvamJnOW44NkVqN1gySDloSTQ4bGdtRVk3QXpTQjdIY0s4T2VJWk8KRXlxM3dzRlNxYnk3emNLY0VzMmFvNDZVd21tYTFOTWtqTEF5WkROemZuKzhWS0pkZnorOQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRREEvVm9PS0hjUFBma2UKS0EwZWdndldmaFFxRmJ5a1A4dkRRSitSdG80WG00MlJuNEY5TXRjK3dFZnFPYWhmZTlPSFR6Sms3SUJ2UEdIbQpGa2NoSDNWOVRNQ3NWYjJJc2FFemlmeDRZQU9ZL0dlRlErMDNMNm1BaDdCb3B3dm9XcERwdDN1blFqek8zSXE0CkI2QXNIMGxMOWpMRmdabHhkOHJnV0oyWXVZbjU4V1NpTWNqQlZtdVdkbTZyTTFmVUNLUWZYQVVLL2dGUlBpa0QKR09wTGNJTzJCRjMweXMxTGRYaXArS2M3WDQ3ZXNjNDRpUmV3dGU4ZURYb0NERmhyelFEcnZBemQ2T0FGcFU5UQpiV0JOLy9mKzRWekVjdkdXZjMvd3RnOW9SRlVtZDJxZHVXVVhIaUhaeExZdkIzSGF3TjFYSk9mZVV3VXNZdjAvClFvbUxvdEFQQWdNQkFBRUNnZ0VBTXhJWWhjeWhqVEFLUDdlN21Rb3pGY1R4a3gyRGVUZkV0VnZobms3Z0ZWRTkKeW42YVpzWlFmYk9tbEU1RHgxamVabDFINmJ0SVZhZDJCTXg2Y0VLQjlmR2N2ejVGVk9va3paM0RhUnVIZURHNwpOMkg5WVhCRWU5WHNraFU2cW5kbEIrUmRYYXJDcXI5a0drVXlWdHJFcTh4d0xTSVp1QlJLWk1vdWtsN3ZLMndHCjZUbXVSb3JmOU0zZWpzTkJLKzJGMjh3TnZlSHBTQWpDSUNEQUYyUFBGOEtheFlHdXZOU0NIMXE3cXhvN3o4dnYKKzQ2Wm93M1hKWllHYzZRaW12TGxXWGQwbDlMSk95NStvSElpZnN3S2FHbjZxUFlmWUxielU2bFhINCs1dk5PTQppemRJYkRQdE1ZS2RsT2thTFRFRS9nM3ZLdEJkSnNwNGQvQXVudGpLV1FLQmdRRHk3a2JWWnpWNDdmOWlZYlQ3CmxaTGpxL1hPMm5uMnV0RHdDNnVIeDFzaHgrWmdGdnIxZXNGdW5ZRmxIMHpKZjlKVFpsSzJQbTRpc0JsSGZXaVoKZU92VWZadUk5M3dvV1hRNzhZNm9BTVZhWWhtRXBzanNpR0JYNDZWUUxwR212OFF2bDZjRlhKcXE1QUkwNXc1WQpuaXRvQjZDVXhRbzRwbWEyWDQzS0s3dHZkUUtCZ1FETFgwVDhQQ0hUZ0prZ05JR1lEWWdoNGliL1E4aTFCTmFkCkcxZTJZc2pBUmlmOTVQTVM3T3cwbnhiSHJ6S1kwa3I4eFFsNWptU2plZWhqVXFvOHNrcjJFeWhwVjBnY0FPeUQKZnZxTGwzUkJIUUQwRXZjek0xQ0lDR1FleWg4dldGa2pnMDZBTmRudHc4dnZtTnBzaDFTajFoQ0JyR1kvWkNUaAphbHg3dVh0MDh3S0JnUUNVa1VTZ25rNEZkd2dJa3Rpc1EvMWhYM2trMkZoZW5FSExqRmVLNGxESmlBZE1ITUc5Ci95VHRFVVpoSVpORVovZXBLWnJMK2NKQlZKRWhONEVRMnZMZk1USTl3WjBjMEJoVjBKVCtDZnFvRy9hZk9hRUgKaHgva29FUXBsVkZlT1VreUVmMERPbThjcy9UbGhha3dhUXNDeENkZzFHQTc1UWhMNElSR2NCaGhRUUtCZ1FDNQo2UjloRFg5R256cGJ6R1Bqb2dzZUhtVFQyUjB6RFhjN0szR2xVdXg5aUNTcTNvNnVjRk1GVDZFOWJaVHRTdUF0CjdkbFplNmZZSVdzazBMNjZ1YW41QlU1ZDdlSUhaM2pPUkZlNUgveXdRVmxMeGNLZzFYbjZ3T0QxbklPaGZqd08KVU15RU83WTZ1bEJGZVEvRFFudEhRanJZcjhiUWtEVitzd0pVUUJ6eHJRS0JnUURrSnlKTExiV0lLa2JEZGZwdQpUNHhVYWJHcWhJQ2w2c0pINDg1NzlXa05XdWpHMkRQNXdGOVkwL1JLV0Q4clFQUDdhR1E4U05vUFpPdHJFd09qCm9HSWE4a3paUmhIVGFrQm9qamYwM2oyNFovRlJCSVRNeFQzdGFRRGVzVGN2cnhrdllYVWJBYU0rZ3BEdWllYUcKRFZsTFJadVdWV0xzakM5ZEpLRmhya3JicVE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t

truststore:
  type: ACCEPT_ALL

routes:
  egress:
    http:
    - clearing: false
      dapsInject: true
      id: HttpsOut

orchestrationManagerConfig:
  enableKubernetes: false

workflow:
  useOrchestration: false
